sudo: required
dist: trusty
language: cpp
compiler:
    - gcc
    - clang
env:
    - CMAKE_BUILD_TYPE=Release
before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
    - sudo add-apt-repository ppa:nschloe/eigen-backports -y
      if [ "$CC" = "clang" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
      if [ "$CC" = "clang" ]; then echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" | sudo tee /etc/apt/sources.list; fi
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq libboost-python1.54-dev libboost1.54-dev libboost-test1.54-dev liblpsolve55-dev lp-solve
    - sudo apt-get install -qq --force-yes libeigen3-dev
    - sudo apt-get install -qq g++-7 # This is needed for clang too!!
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$CC" = "clang" ]; then sudo apt-get install -qq clang-4.0; fi
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
  - make -j 2
  - ctest -V
branches:
  only:
    - master
notifications:
    email: false
