sudo: required
dist: trusty
language: cpp
compiler:
    - gcc
    - clang
env:
    - CMAKE_BUILD_TYPE=Release
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq libboost1.54-dev libboost-test1.54-dev liblpsolve55-dev
    - sudo apt-get install -qq libeigen3-dev
    - sudo apt-get install -qq g++-4.9
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - if [ "$CC" = "clang" ]; then sudo apt-get install -qq clang-3.4; fi
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
  - make -j 2
  - ctest -V
branches:
  only:
    - master
notifications:
    email: false
